version: "3.7"

services:
    database_mentoring:
        image: postgres
        container_name: database_mentoring
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=mentoring
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=mentoring
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local